# -*- coding: utf-8 -*-
# WARNING! All manual changes to this file will be preserved.
# Generated by: pyside6-uic ui/fibre2uart.ui -o ui/ui.py
################################################################################
from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, QSize, Qt)
from PySide6.QtGui import QAction, QFont
from PySide6.QtWidgets import (
    QComboBox, QFormLayout, QGraphicsView, QHBoxLayout, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPlainTextEdit, QProgressBar,
    QPushButton, QSizePolicy, QSplitter, QStatusBar, QTableWidget,
    QTabWidget, QTextEdit, QToolBar, QTreeWidget, QVBoxLayout, QWidget,
    QTableWidgetItem, QHeaderView, QMenu,
)


class Ui_MainWindow:
    """
    纯布局描述类，由 `pyside6-uic fibre2uart.ui` 生成。
    业务逻辑在 main_window.py 的 MainWindow 中实现。
    """

    def setupUi(self, MainWindow: QMainWindow) -> None:  # noqa: N803
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 900)
        MainWindow.setMinimumSize(QSize(1024, 768))
        MainWindow.setWindowTitle(
            QCoreApplication.translate("MainWindow",
                                       "fibre2uart — 光纤通信管理工具"))

        # ── 动作 ─────────────────────────────────────
        self.actionConnect = QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionConnect.setText(
            QCoreApplication.translate("MainWindow", "连接"))

        self.actionDisconnect = QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionDisconnect.setText(
            QCoreApplication.translate("MainWindow", "断开"))

        self.actionScan = QAction(MainWindow)
        self.actionScan.setObjectName("actionScan")
        self.actionScan.setText(
            QCoreApplication.translate("MainWindow", "扫描设备"))

        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.setText(
            QCoreApplication.translate("MainWindow", "退出"))

        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout.setText(
            QCoreApplication.translate("MainWindow", "关于"))

        # ── 菜单栏 ────────────────────────────────────
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuFile.setTitle(
            QCoreApplication.translate("MainWindow", "文件(&F)"))
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHelp.setTitle(
            QCoreApplication.translate("MainWindow", "帮助(&H)"))
        MainWindow.setMenuBar(self.menuBar)

        # ── 工具栏 ────────────────────────────────────
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        # ── 状态栏 ────────────────────────────────────
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        # ── 中心 widget ───────────────────────────────
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        root_layout = QVBoxLayout(self.centralwidget)
        root_layout.setSpacing(2)
        root_layout.setContentsMargins(4, 4, 4, 4)

        # ── 连接栏控件（放入工具栏）────────────────────
        self.labelPort = QLabel("串口:", self.toolBar)
        self.comboPort = QComboBox(self.toolBar)
        self.comboPort.setObjectName("comboPort")
        self.comboPort.setMinimumWidth(160)
        self.comboPort.setEditable(True)

        self.labelBaud = QLabel("波特率:", self.toolBar)
        self.comboBaud = QComboBox(self.toolBar)
        self.comboBaud.setObjectName("comboBaud")
        for baud in ("9600", "38400", "57600", "115200", "230400", "460800", "700000", "921600", "1000000", "2000000"):
            self.comboBaud.addItem(baud)
        self.comboBaud.setCurrentIndex(8)  # 默认 1000000

        self.btnConnect = QPushButton("连接", self.toolBar)
        self.btnConnect.setObjectName("btnConnect")
        self.btnConnect.setMinimumWidth(80)

        self.btnScan = QPushButton("扫描设备", self.toolBar)
        self.btnScan.setObjectName("btnScan")
        self.btnScan.setMinimumWidth(100)
        self.btnScan.setEnabled(False)

        self.btnReadVersion = QPushButton("读取版本号", self.toolBar)
        self.btnReadVersion.setObjectName("btnReadVersion")
        self.btnReadVersion.setMinimumWidth(100)
        self.btnReadVersion.setEnabled(False)

        self.labelStatus = QLabel("● 未连接", self.toolBar)
        self.labelStatus.setObjectName("labelStatus")
        self.labelStatus.setStyleSheet("color: gray;")

        # ── 主垂直分割器 ──────────────────────────────
        self.splitterMain = QSplitter(Qt.Vertical, self.centralwidget)
        self.splitterMain.setObjectName("splitterMain")
        self.splitterMain.setChildrenCollapsible(False)

        # ── 上半：水平分割器 ──────────────────────────
        self.splitterTop = QSplitter(Qt.Horizontal, self.splitterMain)
        self.splitterTop.setObjectName("splitterTop")
        self.splitterTop.setChildrenCollapsible(False)

        # ── 左侧 TabWidget ────────────────────────────
        self.tabLeft = QTabWidget(self.splitterTop)
        self.tabLeft.setObjectName("tabLeft")
        self.tabLeft.setMinimumWidth(300)

        # Tab 1: 设备树
        self.tabDeviceTree = QWidget()
        self.tabDeviceTree.setObjectName("tabDeviceTree")
        vDevTree = QVBoxLayout(self.tabDeviceTree)
        vDevTree.setContentsMargins(0, 0, 0, 0)
        self.deviceTreeWidget = QTreeWidget(self.tabDeviceTree)
        self.deviceTreeWidget.setObjectName("deviceTreeWidget")
        self.deviceTreeWidget.setHeaderLabels(["设备 / 地址 / 状态"])
        vDevTree.addWidget(self.deviceTreeWidget)
        self.tabLeft.addTab(self.tabDeviceTree, "设备树")

        # Tab 2: 拓扑图
        self.tabTopology = QWidget()
        self.tabTopology.setObjectName("tabTopology")
        vTopo = QVBoxLayout(self.tabTopology)
        vTopo.setContentsMargins(0, 0, 0, 0)
        self.topologyView = QGraphicsView(self.tabTopology)
        self.topologyView.setObjectName("topologyView")
        vTopo.addWidget(self.topologyView)
        self.tabLeft.addTab(self.tabTopology, "拓扑图")

        # Tab 3: 通信测试
        self.tabThroughput = QWidget()
        self.tabThroughput.setObjectName("tabThroughput")
        vThroughput = QVBoxLayout(self.tabThroughput)
        vThroughput.setContentsMargins(0, 0, 0, 0)
        self.throughputWidget = QLabel("通信测试占位")  # 将被 ThroughputTestPanel 替换
        self.throughputWidget.setObjectName("throughputWidget")
        vThroughput.addWidget(self.throughputWidget)
        self.tabLeft.addTab(self.tabThroughput, "通信测试")

        # Tab 4: 指令测试
        self.tabCmdTest = QWidget()
        self.tabCmdTest.setObjectName("tabCmdTest")
        vCmdTest = QVBoxLayout(self.tabCmdTest)
        vCmdTest.setContentsMargins(0, 0, 0, 0)
        self.cmdTestWidget = QLabel("指令测试占位")  # 将被 CmdTestPanel 替换
        self.cmdTestWidget.setObjectName("cmdTestWidget")
        vCmdTest.addWidget(self.cmdTestWidget)
        self.tabLeft.addTab(self.tabCmdTest, "指令测试")

        # Tab 4: 路由表
        self.tabRouteTable = QWidget()
        self.tabRouteTable.setObjectName("tabRouteTable")
        vRoute = QVBoxLayout(self.tabRouteTable)
        vRoute.setContentsMargins(0, 0, 0, 0)
        self.routeTableWidget = QTableWidget(0, 3, self.tabRouteTable)
        self.routeTableWidget.setObjectName("routeTableWidget")
        self.routeTableWidget.setHorizontalHeaderLabels(
            ["逻辑地址", "路由路径", "has485"])
        self.routeTableWidget.horizontalHeader().setStretchLastSection(True)
        vRoute.addWidget(self.routeTableWidget)
        self.tabLeft.addTab(self.tabRouteTable, "路由表")

        # ── 右侧 TabWidget ────────────────────────────
        self.tabRight = QTabWidget(self.splitterTop)
        self.tabRight.setObjectName("tabRight")
        self.tabRight.setMinimumWidth(400)

        # Tab 1: 节点详情
        self.tabNodeDetail = QWidget()
        self.tabNodeDetail.setObjectName("tabNodeDetail")
        formDetail = QFormLayout(self.tabNodeDetail)
        self.lblModel    = QLabel("—"); formDetail.addRow("型号:",    self.lblModel)
        self.lblUuid     = QLabel("—"); formDetail.addRow("UUID:",    self.lblUuid)
        self.lblAddr     = QLabel("—"); formDetail.addRow("逻辑地址:", self.lblAddr)
        self.lblPortPath = QLabel("—"); formDetail.addRow("路由路径:", self.lblPortPath)
        self.lblPorts    = QLabel("—"); self.lblPorts.setWordWrap(True)
        formDetail.addRow("端口信息:", self.lblPorts)
        # 终端口专用统计行（选中终端口时显示）
        self._lblTermTxLabel  = QLabel("TX:");   self.lblTermTx  = QLabel("—")
        self._lblTermRxLabel  = QLabel("RX:");   self.lblTermRx  = QLabel("—")
        self._lblTermOvLabel  = QLabel("溢出:"); self.lblTermOv  = QLabel("—")
        formDetail.addRow(self._lblTermTxLabel, self.lblTermTx)
        formDetail.addRow(self._lblTermRxLabel, self.lblTermRx)
        formDetail.addRow(self._lblTermOvLabel, self.lblTermOv)
        for w in (self._lblTermTxLabel, self.lblTermTx,
                  self._lblTermRxLabel, self.lblTermRx,
                  self._lblTermOvLabel, self.lblTermOv):
            w.setVisible(False)
        self.tabRight.addTab(self.tabNodeDetail, "节点详情")

        # Tab 2: 单指令发送
        self.tabCommandPanel = QWidget()
        self.tabCommandPanel.setObjectName("tabCommandPanel")
        vCmd = QVBoxLayout(self.tabCommandPanel)
        formCmd = QFormLayout()
        self.cmdAddr = QLineEdit(); self.cmdAddr.setPlaceholderText("0x0001")
        self.cmdCode = QLineEdit(); self.cmdCode.setPlaceholderText("0x25")
        self.cmdData = QLineEdit(); self.cmdData.setPlaceholderText("00")
        formCmd.addRow("逻辑地址:", self.cmdAddr)
        formCmd.addRow("CMD (hex):", self.cmdCode)
        formCmd.addRow("Data (hex):", self.cmdData)
        self.btnSendCmd = QPushButton("发 送")
        self.btnSendCmd.setObjectName("btnSendCmd")
        self.cmdResult = QTextEdit()
        self.cmdResult.setObjectName("cmdResult")
        self.cmdResult.setReadOnly(True)
        self.cmdResult.setPlaceholderText("响应结果将显示在此...")
        vCmd.addLayout(formCmd)
        vCmd.addWidget(self.btnSendCmd)
        vCmd.addWidget(self.cmdResult)
        self.tabRight.addTab(self.tabCommandPanel, "单指令")

        # Tab 3: 固件升级
        self.tabUpgrade = QWidget()
        self.tabUpgrade.setObjectName("tabUpgrade")
        vUpg = QVBoxLayout(self.tabUpgrade)
        hFile = QHBoxLayout()
        self.upgradeFilePath = QLineEdit(); self.upgradeFilePath.setReadOnly(True)
        self.btnChooseFile = QPushButton("选择...")
        self.btnChooseFile.setObjectName("btnChooseFile")
        hFile.addWidget(QLabel("固件文件:"))
        hFile.addWidget(self.upgradeFilePath)
        hFile.addWidget(self.btnChooseFile)
        hTarget = QHBoxLayout()
        self.upgradeTarget = QComboBox()
        self.upgradeTarget.setObjectName("upgradeTarget")
        self.upgradeTarget.addItem("广播（所有节点）")
        hTarget.addWidget(QLabel("目标:"))
        hTarget.addWidget(self.upgradeTarget)
        hTarget.addStretch()
        self.upgradeProgress = QProgressBar()
        self.upgradeProgress.setObjectName("upgradeProgress")
        self.upgradeProgress.setValue(0)
        self.upgradeStatusLabel = QLabel("就绪")
        self.upgradeStatusLabel.setObjectName("upgradeStatusLabel")
        hUpgBtn = QHBoxLayout()
        self.btnStartUpgrade = QPushButton("开始升级")
        self.btnStartUpgrade.setObjectName("btnStartUpgrade")
        self.btnRetryUpgrade = QPushButton("重 试")
        self.btnRetryUpgrade.setObjectName("btnRetryUpgrade")
        self.btnRetryUpgrade.setEnabled(False)
        hUpgBtn.addWidget(self.btnStartUpgrade)
        hUpgBtn.addWidget(self.btnRetryUpgrade)
        vUpg.addLayout(hFile)
        vUpg.addLayout(hTarget)
        vUpg.addWidget(self.upgradeProgress)
        vUpg.addWidget(self.upgradeStatusLabel)
        vUpg.addLayout(hUpgBtn)
        vUpg.addStretch()
        self.tabRight.addTab(self.tabUpgrade, "固件升级")

        self.splitterTop.addWidget(self.tabLeft)
        self.splitterTop.addWidget(self.tabRight)
        self.splitterTop.setSizes([9999, 400])

        # ── 底部：日志 ────────────────────────────────
        self.widgetLog = QWidget(self.splitterMain)
        self.widgetLog.setObjectName("widgetLog")
        self.widgetLog.setMaximumHeight(200)
        vLog = QVBoxLayout(self.widgetLog)
        vLog.setContentsMargins(0, 0, 0, 0)
        hLogBar = QHBoxLayout()
        lbl_log = QLabel("日志")
        lbl_log.setStyleSheet("font-weight:bold;")
        self.logLevelCombo = QComboBox()
        self.logLevelCombo.setObjectName("logLevelCombo")
        for lvl in ("DEBUG", "INFO", "WARNING", "ERROR"):
            self.logLevelCombo.addItem(lvl)
        self.logLevelCombo.setCurrentIndex(1)  # 默认 INFO
        self.btnClearLog = QPushButton("清空")
        self.btnClearLog.setObjectName("btnClearLog")
        hLogBar.addWidget(lbl_log)
        hLogBar.addWidget(self.logLevelCombo)
        hLogBar.addWidget(self.btnClearLog)
        hLogBar.addStretch()
        mono_font = QFont("Monospace")
        mono_font.setPointSize(9)
        self.logViewer = QPlainTextEdit(self.widgetLog)
        self.logViewer.setObjectName("logViewer")
        self.logViewer.setReadOnly(True)
        self.logViewer.setFont(mono_font)
        vLog.addLayout(hLogBar)
        vLog.addWidget(self.logViewer)

        self.splitterMain.addWidget(self.splitterTop)
        self.splitterMain.addWidget(self.widgetLog)
        self.splitterMain.setSizes([600, 200])

        root_layout.addWidget(self.splitterMain)

        # ── 菜单填充 ──────────────────────────────────
        self.menuFile.addAction(self.actionConnect)
        self.menuFile.addAction(self.actionDisconnect)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        # ── 工具栏填充 ────────────────────────────────
        self.toolBar.addWidget(self.labelPort)
        self.toolBar.addWidget(self.comboPort)
        self.toolBar.addSeparator()
        self.toolBar.addWidget(self.labelBaud)
        self.toolBar.addWidget(self.comboBaud)
        self.toolBar.addSeparator()
        self.toolBar.addWidget(self.btnConnect)
        self.toolBar.addWidget(self.btnScan)
        self.toolBar.addWidget(self.btnReadVersion)
        self.toolBar.addSeparator()
        self.toolBar.addWidget(self.labelStatus)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow: QMainWindow) -> None:
        pass
