#!/bin/bash
# !! DO NOT REGENERATE project/ui/ui.py !!
#
# project/ui/ui.py 是【手写维护】的文件（文件头的 "# Generated by pyside6-uic"
# 注释是误导）。运行时 main_window.py 通过 `from ui.ui import Ui_MainWindow`
# 直接导入它，根本不读 project/ui/fibre2uart.ui（后者是不同步的孤儿产物）。
#
# 在这里运行 pyside6-uic 会用 .ui 重新生成的坏代码【覆盖】手写的 ui.py，
# 并丢失手写控件（btnReadVersion / tabThroughput / tabCmdTest / _lblTerm* 标签等）。
# 这正是当初导致应用启动崩溃的根因。
#
# 请直接手工编辑 ui.py。本脚本刻意不做任何事（no-op）。
echo "buildui.sh: no-op. project/ui/ui.py 是手写的，禁止用 pyside6-uic 重新生成。" >&2
echo "请手工编辑 ui.py。（fibre2uart.ui 是不同步的孤儿文件，非真相来源。）" >&2
exit 0
